# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.10

EAPI=8

inherit cargo git-r3

DESCRIPTION="Yet another *fetch utility is aimed at informativeness"
HOMEPAGE="https://github.com/omnitix/scu"
EGIT_REPO_URI="https://github.com/omnitix/scu"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+=" MIT Unicode-DFS-2016"
SLOT="0"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}
